name: Build and deploy ASP.NET Core app to Azure Web App

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore
        working-directory: ./Backend

      - name: Build
        run: dotnet build --configuration Release --no-restore
        working-directory: ./Backend

      - name: Publish
        run: dotnet publish --configuration Release --no-build --output ./publish
        working-directory: ./Backend

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: azul53-api
          slot-name: production
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: ./Backend/publish
